import React from 'react';
import {Inter } from 'next/font/google';
import "./global.css";


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: "Create Next app",
    Description: " Generated by create next app",
};


    function RootLayout({ children }) {
  return (
    <div>
      <h1>Posts</h1>
      {children}
    </div>
  );
}

export default RootLayout;